---
title: "cleaning"
output: html_document
---

```{r message=FALSE, warning=FALSE}

library(tidyverse)
library(janitor)
library(moderndive)
library(aspace)

options(scipen = 999)

`%not_in%` = Negate(`%in%`)

```

```{r message=FALSE, warning=FALSE}
shot_attempts_all <- read_csv("data/shot_attempts_all.csv")
nba_player_ids <- read_csv("data/NBA_Player_IDs.csv")
stats15_16 <- read_csv("data/stats15_16.csv")
```


```{r}
#remove rows where shooter is not on court
#remove rows where any coordinate = 0.00000
shot_attempts_all <- shot_attempts_all %>% 
  mutate_at(vars(contains("id")), funs(as.character(.))) %>% 
  mutate(game_clock = q_game_clock-(quarter*1000),
        no_shooter_flag = case_when(shooter_id == p1_id ~ 1,
                                    shooter_id == p2_id ~ 2,
                                    shooter_id == p3_id ~ 3,
                                    shooter_id == p4_id ~ 4,
                                    shooter_id == p5_id ~ 5,
                                    shooter_id == p6_id ~ 6,
                                    shooter_id == p7_id ~ 7,
                                    shooter_id == p8_id ~ 8,
                                    shooter_id == p9_id ~ 19,
                                    shooter_id == p10_id ~ 10,
                                    TRUE ~ 0
                                    ),
         zero_cord_flag = case_when(ball_x_loc == 0 ~ 0,
                                    ball_y_loc == 0 ~ 0,
                                    p1_x_loc == 0 ~ 0,
                                    p1_y_loc == 0 ~ 0,
                                    p2_x_loc == 0 ~ 0,
                                    p2_y_loc == 0 ~ 0,
                                    p3_x_loc == 0 ~ 0,
                                    p3_y_loc == 0 ~ 0,
                                    p4_x_loc == 0 ~ 0,
                                    p4_y_loc == 0 ~ 0,
                                    p5_x_loc == 0 ~ 0,
                                    p5_y_loc == 0 ~ 0,
                                    p6_x_loc == 0 ~ 0,
                                    p7_y_loc == 0 ~ 0,
                                    p8_x_loc == 0 ~ 0,
                                    p8_y_loc == 0 ~ 0,
                                    p9_x_loc == 0 ~ 0,
                                    p9_y_loc == 0 ~ 0,
                                    p10_x_loc == 0 ~ 0,
                                    p10_y_loc == 0 ~ 0,
                                    TRUE ~ 1
                                    ),
         
         ) %>% 
  filter(no_shooter_flag != 0, zero_cord_flag > 0) %>% 
  mutate_at(vars(contains("id")), funs(as.character(.))) %>% 
  mutate(game_clock = q_game_clock-(quarter*1000)) %>% 
  select(game_id, quarter, game_clock, everything(), -c(no_shooter_flag, zero_cord_flag, shot_attempted_flag, grid_type))

```


```{r distances}

#compute each player's distance from the ball
shot_attempts_all_dist <- shot_attempts_all %>% 
  mutate(p1_dist_from_ball = sqrt(((ball_x_loc-p1_x_loc)^2)+((ball_y_loc-p1_y_loc)^2)),
         p2_dist_from_ball = sqrt(((ball_x_loc-p2_x_loc)^2)+((ball_y_loc-p2_y_loc)^2)),
         p3_dist_from_ball = sqrt(((ball_x_loc-p3_x_loc)^2)+((ball_y_loc-p3_y_loc)^2)),
         p4_dist_from_ball = sqrt(((ball_x_loc-p4_x_loc)^2)+((ball_y_loc-p4_y_loc)^2)),
         p5_dist_from_ball = sqrt(((ball_x_loc-p5_x_loc)^2)+((ball_y_loc-p5_y_loc)^2)),
         p6_dist_from_ball = sqrt(((ball_x_loc-p6_x_loc)^2)+((ball_y_loc-p6_y_loc)^2)),
         p7_dist_from_ball = sqrt(((ball_x_loc-p7_x_loc)^2)+((ball_y_loc-p7_y_loc)^2)),
         p8_dist_from_ball = sqrt(((ball_x_loc-p8_x_loc)^2)+((ball_y_loc-p8_y_loc)^2)),
         p9_dist_from_ball = sqrt(((ball_x_loc-p9_x_loc)^2)+((ball_y_loc-p9_y_loc)^2)),
         p10_dist_from_ball = sqrt(((ball_x_loc-p10_x_loc)^2)+((ball_y_loc-p10_y_loc)^2))
         )

write.csv(shot_attempts_all_dist, 'data/shot_attempts_all_dist.csv', row.names = FALSE)

```



#import dataset from python script

```{r message=FALSE}
shot_attempts_all_nearest_def <- read_csv("data/shot_attempts_all_nearest_def.csv")
```


```{r}
less_than_two <- shot_attempts_all_nearest_def %>% 
  mutate(ball_to_shooter = sqrt(((shooter_x_loc-ball_x_loc)^2) + ((shooter_y_loc-ball_y_loc)^2))) %>% 
  arrange(-ball_to_shooter) %>% 
  select(ball_to_shooter, shooter_id, shooter_x_loc, shooter_y_loc, shot_team_id, ball_x_loc, ball_y_loc, everything()) %>% 
  filter(ball_to_shooter < 2)

```




```{r}
less_than_two <- less_than_two %>% 
  mutate(points = case_when(shot_type == "3PT Field Goal" & event_type == "Made Shot" ~ 3,
                            shot_type == "2PT Field Goal" & event_type == "Made Shot" ~ 2,
                            event_type == "Missed Shot" ~ 0
                            ),
         points_class = as.character(points),
         shot_type_num = ifelse(shot_type == "2PT Field Goal", 2, 3),
         shooter_id = as.character(shooter_id),
         made_missed = ifelse(points == 2 | points == 3, 1, 0),
         shooter_to_hoop = shooter_to_hoop(shooter_x_loc, shooter_y_loc),
         nearest_def_dist = sqrt(((shooter_x_loc-nearest_def_x_loc)^2) + ((shooter_y_loc-nearest_def_y_loc)^2)),
         def_angle = def_angle(shooter_x_loc, shooter_y_loc, nearest_def_x_loc, nearest_def_y_loc),
         def_angle = ifelse(is.na(def_angle), 91, def_angle),
         rim_jump = case_when(grepl("Dunk", less_than_two$action_type, ignore.case = TRUE) ~ "rim",
                              grepl("Lay", less_than_two$action_type, ignore.case = TRUE) ~ "rim",
                              TRUE ~ "jump"
                              ),
         nearest_def_dist_round = case_when(nearest_def_dist <= .25 ~ 0,
                                            nearest_def_dist > .25 & nearest_def_dist <= .75 ~ .5,
                                            nearest_def_dist > .75 & nearest_def_dist <= 1.25 ~ 1,
                                            nearest_def_dist > 1.25 & nearest_def_dist <= 1.75 ~ 1.5,
                                            nearest_def_dist > 1.75 & nearest_def_dist <= 2.25 ~ 2,
                                            nearest_def_dist > 2.25 & nearest_def_dist <= 2.75 ~ 2.5,
                                            nearest_def_dist > 2.75 & nearest_def_dist <= 3.25 ~ 3,
                                            nearest_def_dist > 3.25 & nearest_def_dist <= 3.75 ~ 3.5,
                                            nearest_def_dist > 3.75 & nearest_def_dist <= 4.25 ~ 4,
                                            nearest_def_dist > 4.25 & nearest_def_dist <= 4.75 ~ 4.5,
                                            nearest_def_dist > 4.75 & nearest_def_dist <= 5.25 ~ 5,
                                            nearest_def_dist > 5.25 & nearest_def_dist <= 5.75 ~ 5.5,
                                            nearest_def_dist > 5.75 & nearest_def_dist <= 6.25 ~ 6,
                                            nearest_def_dist > 6.25 & nearest_def_dist <= 6.75 ~ 6.5,
                                            nearest_def_dist > 6.75 & nearest_def_dist <= 7.25 ~ 7,
                                            nearest_def_dist > 7.25 & nearest_def_dist <= 7.75 ~ 7.5,
                                            nearest_def_dist > 7.75 & nearest_def_dist <= 8.25 ~ 8,
                                            nearest_def_dist > 8.25 ~ 9,
                                            )
         ) %>% 
  group_by(shooter_id) %>% 
  mutate(n = n(), pps = sum(points)/n) %>% 
  ungroup()


# less_than_two %>%
#   filter_all(any_vars(is.na(.)))
```


```{r}
stats15_16 <- stats15_16 %>% 
  clean_names() %>% 
  select(-rk, fgp = fg_percent, tpm = x3p, tpa = x3pa, tpp = x3p_percent, tpfgm = x2p, tpfga = x2pa, tpfgp = x2p_percent, efg = e_fg_percent)

less_than_two <- less_than_two %>% 
  left_join(stats15_16, by = c('player_name' = 'player'))
  
write.csv(less_than_two, 'data/less_than_two.csv', row.names = FALSE)
```







